name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point you're experiencing
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: Describe your proposed solution in detail
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: Describe alternative solutions or workarounds you've considered

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Provide a specific use case or example
      placeholder: |
        Example scenario:
        1. User wants to...
        2. Currently they have to...
        3. With this feature they could...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - agent (Agent runtime)
        - communication (Message passing, references)
        - orchestration (Workflows, patterns)
        - server (looms server)
        - cli (Command-line tools)
        - observability (Tracing, metrics)
        - prompts (Prompt management)
        - fabric (Backend interface)
        - shuttle (Tool system)
        - proto (Protocol buffers)
        - documentation
        - multiple components
        - other (specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (blocks major use case)
        - High (important for productivity)
        - Medium (nice to have)
        - Low (small improvement)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Have you thought about implementation?
      options:
        - label: I can help implement this feature
        - label: This requires proto changes
        - label: This requires breaking changes
        - label: This affects multiple components
        - label: This needs documentation updates

  - type: textarea
    id: examples
    attributes:
      label: Example Code or Configuration
      description: Provide example usage if applicable
      placeholder: |
        ```go
        // Example of how this feature would be used
        ```
      render: go

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Does this depend on other features or issues?
      placeholder: |
        - Depends on #123
        - Related to #456

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with Loom's goals (agent orchestration)
          required: true
        - label: I have provided a clear use case
          required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, diagrams, or references
      placeholder: Add any other context, mockups, or references here
